var roundLoader = {
    currentRound:3,
    rounds:[
    {
        roundId:1,
        roundTitle:"第一轮",
        roundSubTitle:"小组赛",
        roundDateRange:"2018.6.10 - 6.22",
        countdownSeconds:36862,
        freeSalary:90000000,
        topSalary:120000000,
        matchs:[
            {
                title:"D组小组赛第1轮",
                host:{
                    icon:"",
                    name:"巴西"
                },
                visit:{
                    icon:"",
                    name:"阿联酋"
                },
                matchTime:"2018-06-18 18:00"
            }
            ,{
                title:"D组小组赛第2轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第3轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第4轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第5轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第2轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
        ]
    }
    ,{
        roundId:1,
        roundTitle:"第一轮",
        roundSubTitle:"小组赛",
        roundDateRange:"2018.6.10 - 6.22",
        countdownSeconds:36862,
        freeSalary:90000000,
        topSalary:120000000,
        matchs:[
            {
                title:"D组小组赛第1轮",
                host:{
                    icon:"",
                    name:"巴西"
                },
                visit:{
                    icon:"",
                    name:"阿联酋"
                },
                matchTime:"2018-06-18 18:00"
            }
            ,{
                title:"D组小组赛第2轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第3轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第4轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第5轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第2轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
        ]
    }
    ,{
        roundId:1,
        roundTitle:"第一轮",
        roundSubTitle:"小组赛",
        roundDateRange:"2018.6.10 - 6.22",
        countdownSeconds:36862,
        freeSalary:90000000,
        topSalary:120000000,
        matchs:[
            {
                title:"D组小组赛第1轮",
                host:{
                    icon:"",
                    name:"巴西"
                },
                visit:{
                    icon:"",
                    name:"阿联酋"
                },
                matchTime:"2018-06-18 18:00"
            }
            ,{
                title:"D组小组赛第2轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第3轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第4轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第5轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
            ,{
                title:"D组小组赛第2轮",
                host:{
                   icon:"",
                   name:"巴西"
                },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
        ]
    }
    ,{
         roundId:1,
         roundTitle:"第一轮",
         roundSubTitle:"小组赛",
         roundDateRange:"2018.6.10 - 6.22",
         countdownSeconds:36862,
         freeSalary:90000000,
         topSalary:120000000,
         matchs:[
         {
             title:"D组小组赛第1轮",
             host:{
                 icon:"",
                 name:"巴西"
             },
             visit:{
                 icon:"",
                 name:"阿联酋"
             },
             matchTime:"2018-06-18 18:00"
         }
         ,{
             title:"D组小组赛第2轮",
             host:{
                icon:"",
                name:"巴西"
             },
              visit:{
                  icon:"",
                  name:"阿联酋"
              },
              matchTime:"2018-06-18 18:00"
          }
         ,{
             title:"D组小组赛第3轮",
             host:{
                icon:"",
                name:"巴西"
             },
              visit:{
                  icon:"",
                  name:"阿联酋"
              },
              matchTime:"2018-06-18 18:00"
          }
         ,{
             title:"D组小组赛第4轮",
             host:{
                icon:"",
                name:"巴西"
             },
              visit:{
                  icon:"",
                  name:"阿联酋"
              },
              matchTime:"2018-06-18 18:00"
          }
         ,{
             title:"D组小组赛第5轮",
             host:{
                icon:"",
                name:"巴西"
             },
              visit:{
                  icon:"",
                  name:"阿联酋"
              },
              matchTime:"2018-06-18 18:00"
          }
         ,{
             title:"D组小组赛第2轮",
             host:{
                icon:"",
                name:"巴西"
             },
              visit:{
                  icon:"",
                  name:"阿联酋"
              },
              matchTime:"2018-06-18 18:00"
          }
     ]
     }
     ,{
         roundId:1,
         roundTitle:"第一轮",
         roundSubTitle:"小组赛",
         roundDateRange:"2018.6.10 - 6.22",
         countdownSeconds:36862,
         freeSalary:90000000,
         topSalary:120000000,
         matchs:[
             {
                 title:"D组小组赛第1轮",
                 host:{
                     icon:"",
                     name:"巴西"
                 },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
             ,{
                 title:"D组小组赛第2轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第3轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第4轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第5轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第2轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
         ]
     }
     ,{
         roundId:1,
         roundTitle:"第一轮",
         roundSubTitle:"小组赛",
         roundDateRange:"2018.6.10 - 6.22",
         countdownSeconds:36862,
         freeSalary:90000000,
         topSalary:120000000,
         matchs:[
             {
                 title:"D组小组赛第1轮",
                 host:{
                     icon:"",
                     name:"巴西"
                 },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
             ,{
                 title:"D组小组赛第2轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第3轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第4轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第5轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第2轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
         ]
     }
     ,{
         roundId:1,
         roundTitle:"第一轮",
         roundSubTitle:"小组赛",
         roundDateRange:"2018.6.10 - 6.22",
         countdownSeconds:36862,
         freeSalary:90000000,
         topSalary:120000000,
         matchs:[
             {
                 title:"D组小组赛第1轮",
                 host:{
                     icon:"",
                     name:"巴西"
                 },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
             ,{
                 title:"D组小组赛第2轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第3轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第4轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第5轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第2轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
         ]
     }
     ,{
         roundId:1,
         roundTitle:"第一轮",
         roundSubTitle:"小组赛",
         roundDateRange:"2018.6.10 - 6.22",
        countdownSeconds:36862,
        freeSalary:90000000,
        topSalary:120000000,
         matchs:[
             {
                 title:"D组小组赛第1轮",
                 host:{
                     icon:"",
                     name:"巴西"
                 },
                 visit:{
                     icon:"",
                     name:"阿联酋"
                 },
                 matchTime:"2018-06-18 18:00"
             }
             ,{
                 title:"D组小组赛第2轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第3轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第4轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第5轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
             ,{
                 title:"D组小组赛第2轮",
                 host:{
                    icon:"",
                    name:"巴西"
                 },
                  visit:{
                      icon:"",
                      name:"阿联酋"
                  },
                  matchTime:"2018-06-18 18:00"
              }
         ]
     }],
}

var roundListStr = "<ul>";

$.each(roundLoader.rounds, function (i, round) {
    roundListStr += "<li><div>"+round.roundTitle+"</div>\n<div>"+round.roundSubTitle+"</div></li>";
});
roundListStr += "</ul>";